### ISSUE TITLE
How to use in Windows? 

### ISSUE THREAD

**Issue by ghost** [ycherkasov/smbios_util#2]
Code not worked ...

```
#include <iostream>

#include "smbios/abstract_smbios_entry.h"
#include "smbios/smbios.h"
#include "smbios/smbios_entry_factory.h"

int main()
{
	smbios::SMBios bios;
	smbios::SMBiosVersion ver = bios.get_smbios_version();
	std::cout << "DMI version: " << ver.major_version << '.' << ver.minor_version << '\n';
	std::cout << "Table size: " << bios.get_table_size() << '\n';
	std::cout << bios.render_to_description();


	smbios::SMBiosEntryFactory smbios_factory;
	for (const smbios::DMIHeader& header : bios)
	{
		std::cout << "Header ID = " << header.get_type() << '\n';
		std::unique_ptr<smbios::AbstractSMBiosEntry> entry = smbios_factory.create(header, ver);
		if (entry)
		{
			std::cout << entry->render_to_description() << '\n';
		}
	}
}

```

**Comment by yuchdev** [comment]
Could you provide more details, like OS version? Did you try to debug? Which function return error? Does `GetSystemFirmwareTable()` from  `smbios_util/smbios/src/win_bios.cpp` execute without problems?
Because currently the solution works perfectly under Windows in a desktop product (macOS and Linux are left for future though), so it could be a corner case.

**Comment by ghost** [comment]
Windows 10 1909 x64

![](https://i.imgur.com/jRgaO1o.jpg)
![](https://i.imgur.com/KGkJ5IQ.jpg)

**Comment by ghost** [comment]
smbios_entry64_ empty

**Comment by ghost** [comment]
render_to_description return nothing..

**Comment by yuchdev** [comment]
Check GetSystemFirmwareTable() return value. If it's a zero, call ::GetLastError() and check the code. Non-zero value is unlikely, because it's against function description and means memory buffer should be bigger, but I can't deny any possibility

**Comment by ghost** [comment]
GetSystemFirmwareTable not a zero

**Comment by yuchdev** [comment]
It's outside application scope then, and might be connected to last Windows Update. I'll check it out in nearest time.
You also can isolate the problem by calling GetSystemFirmwareTable() in your own console application and check the output
